apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: influxGrafana
  name: infludb-grafana
  namespace: kube-system
spec:
  replicas: 1
  selector:
    name: influxGrafana
  template:
    metadata:
      labels:
        name: influxGrafana
    spec:
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.5
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      - name: grafana
        image: kubernetes/heapster_grafana:v2.1.0
        env:
          - name: "INFLUXDB_SERVICE_URL"
            value: "http://monitoring-influxdb:8086"
        volumeMounts:
        - mountPath: /var
          name: grafana-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
      - name: grafana-storage
        emptyDir: {}
