apiVersion: "v1beta1"
kind: "ReplicationController"
id: "monitoring-influx-grafana-controller"
desiredState: 
  replicas: 1
  replicaSelector:
    name: "influxGrafana"
  podTemplate:
    labels:
      name: "influxGrafana"
    desiredState:
      manifest:
        version: "v1beta1"
        id: "monitoring-influx-grafana-controller"
        containers: 
          - name: "influxdb"
            image: "kubernetes/heapster_influxdb:v0.3"
            ports: 
              - containerPort: 8083
                hostPort: 8083
          - name: "grafana"
            image: "kubernetes/heapster_grafana:v0.4"
            ports: 
              - containerPort: 80
                hostPort: 80
            env: 
              - name: "HTTP_USER"
                value: "admin"
              - name: "HTTP_PASS"
                value: "**None**"
              - name: "INFLUXDB_PROTO"
                value: "https"
              - name: "INFLUXDB_HOST"
                value: '"+window.location.hostname+"/api/v1beta1/proxy/services/monitoring-influxdb'
              - name: "INFLUXDB_PORT"
                value: ""
labels:
  name: "influxGrafana"
