apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: monitoring-influxdb
    kubernetes.io/cluster-service: "true"
  name: monitoring-influxdb
spec:
  targetPort: 8086
  port: 80
  selector:
    name: influxGrafana
